name: Release
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2

    - name: extract_version_info
      run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
      id: extract_version_name       

    - uses: johnyherangi/create-release-notes@main
      id: create-release-notes

    - name: Create Release 
      uses: actions/create-release@v1
      with: 
        tag_name: ${{ steps.extract_version_name.outputs.version }} 
        release_name: ${{ steps.extract_version_name.outputs.version }} 
        body: ${{ steps.create-release-notes.outputs.release-notes }}