name: Release-drafter
on:
  push:
    branches:
      - feature/refactor-autorelease

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: release-drafter/release-drafter@v5
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}