name: Release-drafter
on:
  push:
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: release-drafter/release-drafter@v5
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}